single_frequency_fft:
  name: acquire_m4s_cband_5
  frequency: 3476.47e6
  gain: 40
  sample_rate: 23.04e6
  fft_size: 1024
  nffts: 300
  nskip: 23.04e4
  classification: UNCLASSIFIED
  calibration_adjust: False
