single_frequency_fft:
  name: acquire_m4s_cband_40_56_4096_0
  frequency: 3361520000.0
  gain: 40
  sample_rate: 23040000.0
  fft_size: 4096
  nffts: 56
  nskip: 230400
  classification: UNCLASSIFIED
  calibration_adjust: false
