single_frequency_fft:
  name: acquire_m4s_cband_50_2250_1024_4
  frequency: 3453480000.0
  gain: 50
  sample_rate: 23040000.0
  fft_size: 1024
  nffts: 2250
  nskip: 230400
  classification: UNCLASSIFIED
  calibration_adjust: false
