single_frequency_fft:
  name: acquire_m4s_cband_40_225_1024_8
  frequency: 3545440000.0
  gain: 40
  sample_rate: 23040000.0
  fft_size: 1024
  nffts: 225
  nskip: 230400
  classification: UNCLASSIFIED
  calibration_adjust: false
