single_frequency_fft:
  name: acquire_m4s_cband_45_7_32768_2
  frequency: 3407500000.0
  gain: 45
  sample_rate: 23040000.0
  fft_size: 32768
  nffts: 7
  nskip: 230400
  classification: UNCLASSIFIED
  calibration_adjust: false
