single_frequency_fft:
  name: acquire_m4s_cband_7
  frequency: 3522.45e6
  gain: 60
  sample_rate: 23.04e6
  fft_size: 1024
  nffts: 3000
  nskip: 23.04e4
  classification: UNCLASSIFIED
  calibration_adjust: False
